{{- if .Values.inngest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beema.fullname" . }}-inngest
  labels:
    app.kubernetes.io/name: inngest
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8288
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: inngest
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
