{{- if .Values.studio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beema.fullname" . }}-studio
  labels:
    app.kubernetes.io/name: {{ include "beema.name" . }}-studio
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: studio
spec:
  type: {{ .Values.studio.service.type }}
  ports:
    - port: {{ .Values.studio.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "beema.name" . }}-studio
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
