apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beema-studio.fullname" . }}
  labels:
    {{- include "beema-studio.labels" . | nindent 4 }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
